"""
Configuration settings for Predator: Badlands simulation
"""

# Grid Settings
GRID_WIDTH = 30
GRID_HEIGHT = 30
WRAPPING_ENABLED = True

# Agent Initial Stats
DEK_INITIAL_HEALTH = 100
DEK_INITIAL_STAMINA = 100
DEK_INITIAL_HONOUR = 0
DEK_INITIAL_POSITION = (5, 5)

THIA_INITIAL_HEALTH = 50  # Damaged
THIA_INITIAL_POSITION = (7, 5)

ADVERSARY_INITIAL_HEALTH = 500
ADVERSARY_INITIAL_POSITION = (25, 25)

# Movement Costs
MOVE_STAMINA_COST = 2
CARRY_THIA_STAMINA_COST = 5
COMBAT_STAMINA_COST = 10

# Combat Settings
BASIC_ATTACK_DAMAGE = 10
TROPHY_HONOUR_GAIN = 15
ADVERSARY_DEFEAT_HONOUR = 100

# Creature Settings
NUM_WILDLIFE = 15
WILDLIFE_HEALTH = 30
WILDLIFE_DAMAGE = 5

# Clan Settings
NUM_CLAN_MEMBERS = 3
HONOUR_THRESHOLD_RESPECT = 50
HONOUR_THRESHOLD_CHALLENGE = 30

# Simulation Settings
MAX_TURNS = 500
ENERGY_REGEN_RATE = 1  # Per turn if resting

# Visualization
CELL_SIZE = 20
FPS = 5  # Frames per second for animation

# Colors (for visualization)
COLOR_EMPTY = '#D2B48C'  # Desert tan
COLOR_DEK = '#00FF00'
COLOR_THIA = '#87CEEB'
COLOR_ADVERSARY = '#8B0000'
COLOR_WILDLIFE = '#8B4513'
COLOR_CLAN = '#FFD700'
COLOR_OBSTACLE = '#696969'